language: java
jdk: openjdk7

env:
  global:
  - TERM=dumb

  # FTP credentials
  - secure: "Kr1v5LVVU71qz/5B4LLFFz0QXl2zp0cguiEc9vgowFKQNCLqm8GBPeVHf9UeusII0I6xe6KEW2MJQKs/8bwui8FJ32DSZmo6ZeIHH/f8HYNU0Gv5sn9JnYFBpviO6wsHeQD5opfkT8yVOIcbRKj4nm18BdCqGqZz4H6itIqk5KA="
  - secure: "NBsosd36iAWor28wf554em6M9VvzoK3lPUC6MQsj/SrbFDk1VUFlj3+qbu2xuS+Gr3nDqyXXxwsgbAD2dVZn8WtdYMrBy1UF5PsrYICnAdIcvo3+mCm9n9uhpOc/cJGvNDnM9k2zgbJtgo2BmuhG6tWd/0CKPFBHtsOPO0NAifA="
  - secure: "IGnwLje6dFPhbsqmXewzvT/ipgLw3Py1yscBIThsEnvAsMUhLpuSE0/Nr20Z8C5wIbn5bDPhZsao37KpCcR51E7CopVu2PLoml1jiic1y5ZC9r+mm3iGH8RV1W/b2D6N2fTHuzLUtVp23jIuF0rLBik60+K9z/lGrlsDpkIcKoI="
  
branches:
  only:
  - master
  - develop

notifications:
  email: false
  irc: chat.freenode.net#syncany

before_install:
  # Standard Stuff
  - sudo apt-get update
  - sudo apt-get install -y -q lftp
  - lftp -v
  - mkdir ~/.gradle 2> /dev/null || true
  - echo "org.gradle.daemon=true" > ~/.gradle/gradle.properties

  # Debian Packaging
  - sudo apt-get install -y -q dh-make devscripts debhelper bash-completion
  - gpg --version
  - debuild --version
  - perl -v

install:
  # Disable default travis behavior 'gradle assemble'
  - ./gradlew -v

script:
  # Be safe and clean!
  - ./gradlew clean

  # Build JAR and Debian DEB
  - ./gradlew pluginJar
  - ./gradlew pluginDebianDeb  

  # Upload JARs and DEBs
  - core/gradle/lftp/lftpuploadplugin.sh
